/*
 *
 * Task code generated by SAS Studio 3.71 
 *
 * Generated on '10/23/18, 11:19 PM' 
 * Generated by 'gouta' 
 * Generated on server 'DESKTOP-EF15HE2' 
 * Generated on SAS platform 'X64_8PRO WIN' 
 * Generated on SAS version '9.04.01M3P06242015' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134' 
 * Generated on web client 'http://localhost:62696/main?locale=en_US&zone=GMT-05%253A00&sutoken=%257B50BC5E92-3ECB-4520-98B0-A2AEFA856669%257D' 
 *
 */

libname class 'C:\Temp\BAN5733\DATA'; *Change library path as needed*/;

data a; set class.catalog_rfm;
trf_recency=-1*recency; *reverse coding recency*/;

Title ' Analysis of frequency variable';
proc freq data=a;
tables frequency; * not using recency and money beacuse output gets too large*/;
run;

Title 'Quantiles for Frequency';
proc univariate data=a;
   var frequency ;
   output out=percentilesF pctlpts=0 to 100 by 20 pctlpre=F;
   Proc print data=percentilesF;
run;

 Title 'Quantiles for Recency';
proc univariate data=a ;
   var trf_recency ;
   output out=percentilesR pctlpts=0 to 100 by 20 pctlpre=R;
   Proc print data=percentilesR;    
run;

Title 'Quantiles for Money';
proc univariate data=a ;
   var Money ;
   output out=percentilesM pctlpts=0 to 100 by 20 pctlpre=M;
   Proc print data=percentilesM ;


run;
 
proc rank data=a groups=5 ties = low out=ranked_catalogue;
      var trf_Recency frequency money;
      ranks rank_R rank_F rank_M;
   run;


Title 'Analysis of R, F and M codes separately';   
Proc freq; tables rank_R rank_F rank_M;
run;
* Look at the distinct values of R, F and M ranks that SAS came up with*;
* In this case, R and F ranks have 5 levels each from 0 to 4 and M rank has 4 levels 0,2,3,4*; 
* Then convert them to traditional RFM coding going from 1 to 5 for R, F and M*;

   
data Temp; set ranked_catalogue;
rank_R=rank_R+1; * converting R to 5 levels to start at 1*/;
rank_F=rank_F+1; * converting F to 5 levels to start at 1*/;
rank_M= rank_M+1; * converting F to 5 levels to start at 1*/;


Title 'Analysis of R, F and M codes separately after making sure all of them start with level 1';   
Proc freq; tables rank_R rank_F rank_M;
run;

Dat temp1; set temp;
Title ' Response by RFM groups';
RFM = rank_R||rank_F||rank_M; *Cocatenating R, F and M to create RFM */;
Proc sort; by RFM;
Proc Means; var Response; By RFM;
Run;

